language: node_js
node_js:
- "10.9.0"
branches:
  only:
  - cypress
before_script:
- npm install -g @angular/cli
script:
- echo "Deploy!!"
- npm install
- ng build
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project supereleven-2019 --token $FIREBASE_TOKEN
